apiVersion: v1
kind: Service
metadata:
 namespace: fabric8
 name: mongo
 labels:
    name: mongo
spec:
 ports:
 - port: 27017
   targetPort: 27017
 clusterIP: None
 selector:
   role: mongo

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: fabric8
  name: mongo
spec:
   serviceName: "mongo"
   replicas: 3
   template:
     metadata:
       labels:
         role: mongo
         environment: test
     spec:
       serviceAccount: nfs-client-provisioner
       terminationGracePeriodSeconds: 10
       containers:
         - name: mongo
           image: mongo
           command:
              - mongod
              - "--replSet"
              - rs0
              - "--smallfiles"
              - "--noprealloc"
           ports:
            - containerPort: 27017
           volumeMounts:
           - name: mongo-persistent-storage
             mountPath: /data/db
         - name: mongo-sidecar
           image: cvallance/mongo-k8s-sidecar
           env:
           - name: MY_MONGO 
             value: "role=mongo,environment=test" 
   volumeClaimTemplates:
         - metadata:
             name: mongo-persistent-storage
             annotations:
                volume.beta.kubernetes.io/storage-class: "nfs"    
           spec:
             accessModes: ["ReadWriteOnce"]
             resources:
                requests:
                  storage: 1Gi
